### PR TITLE
remove styled components

### PR DESCRIPTION
**Pull request by kalidiagne**
removed move of styled components and cleanup

### CODE REVIEW

**Review by AndrewCLu — APPROVED** [review]
Woo! LGTM. Can you remove the `styled-components` library as well?

**Comment by RiverRuby** [comment]
Amazing, still need to test all the parts of the site to make sure styling is the same, but this looks great.

Can we also get rid of `StyledComponentsRegistry` as in `app/layout.tsx`? And references to styled-components in `next.config.js` and anywhere else in configs?

**Comment by kalidiagne** [comment]
> Amazing, still need to test all the parts of the site to make sure styling is the same, but this looks great.
> 
> Can we also get rid of `StyledComponentsRegistry` as in `app/layout.tsx`? And references to styled-components in `next.config.js` and anywhere else in configs?

Need to clean up just `HomeScreen` component and we can remove this as well

**Comment by kalidiagne** [comment]
@AndrewCLu @vb7401 clean up done, can you please double check?

**Comment by RiverRuby** [comment]
Score reveal modal is changed. Current:
image

Past:
image

**Comment by RiverRuby** [comment]
Text in backup version is changed. Current:
image

Past:
image

**Comment by kalidiagne** [comment]
@vb7401 both fixed ! thank you! :)

**Pull request merged**
